// @author  ding.shichen
// @email   foreverhuiqiao@126.com
// @date    2023-01-28

package com.enhe.endpoint.database

enum class MybatisJdbcType {
    ARRAY,
    BIT,
    TINYINT,
    SMALLINT,
    INTEGER,
    BIGINT,
    FLOAT,
    REAL,
    DOUBLE,
    NUMERIC,
    DECIMAL,
    CHAR,
    VARCHAR,
    LONGVARCHAR,
    DATE,
    TIME,
    TIMESTAMP,
    BINARY,
    VARBINARY,
    LONGVARBINARY,
    NULL,
    OTHER,
    BLOB,
    CLOB,
    BOOLEAN,
    CURSOR,
    UNDEFINED,
    NVARCHAR,
    NCHAR,
    NCLOB,
    STRUCT,
    JAVA_OBJECT,
    DISTINCT,
    REF,
    DATALINK,
    ROWID,
    LONGNVARCHAR,
    SQLXML,
    DATETIMEOFFSET,
    TIME_WITH_TIMEZONE,
    TIMESTAMP_WITH_TIMEZONE,
}